package com.example.android__theaudiodb.model.dto

import com.google.gson.annotations.SerializedName


data class ArtistsDTO (
    @SerializedName("idArtist"           ) var idArtist           : String? = null,
    @SerializedName("strArtist"          ) var strArtist          : String? = null,
    @SerializedName("strArtistStripped"  ) var strArtistStripped  : String? = null,
    @SerializedName("strArtistAlternate" ) var strArtistAlternate : String? = null,
    @SerializedName("strLabel"           ) var strLabel           : String? = null,
    @SerializedName("idLabel"            ) var idLabel            : String? = null,
    @SerializedName("intFormedYear"      ) var intFormedYear      : String? = null,
    @SerializedName("intBornYear"        ) var intBornYear        : String? = null,
    @SerializedName("intDiedYear"        ) var intDiedYear        : String? = null,
    @SerializedName("strDisbanded"       ) var strDisbanded       : String? = null,
    @SerializedName("strStyle"           ) var strStyle           : String? = null,
    @SerializedName("strGenre"           ) var strGenre           : String? = null,
    @SerializedName("strMood"            ) var strMood            : String? = null,
    @SerializedName("strWebsite"         ) var strWebsite         : String? = null,
    @SerializedName("strFacebook"        ) var strFacebook        : String? = null,
    @SerializedName("strTwitter"         ) var strTwitter         : String? = null,
    @SerializedName("strBiographyEN"     ) var strBiographyEN     : String? = null,
    @SerializedName("strBiographyDE"     ) var strBiographyDE     : String? = null,
    @SerializedName("strBiographyFR"     ) var strBiographyFR     : String? = null,
    @SerializedName("strBiographyCN"     ) var strBiographyCN     : String? = null,
    @SerializedName("strBiographyIT"     ) var strBiographyIT     : String? = null,
    @SerializedName("strBiographyJP"     ) var strBiographyJP     : String? = null,
    @SerializedName("strBiographyRU"     ) var strBiographyRU     : String? = null,
    @SerializedName("strBiographyES"     ) var strBiographyES     : String? = null,
    @SerializedName("strBiographyPT"     ) var strBiographyPT     : String? = null,
    @SerializedName("strBiographySE"     ) var strBiographySE     : String? = null,
    @SerializedName("strBiographyNL"     ) var strBiographyNL     : String? = null,
    @SerializedName("strBiographyHU"     ) var strBiographyHU     : String? = null,
    @SerializedName("strBiographyNO"     ) var strBiographyNO     : String? = null,
    @SerializedName("strBiographyIL"     ) var strBiographyIL     : String? = null,
    @SerializedName("strBiographyPL"     ) var strBiographyPL     : String? = null,
    @SerializedName("strGender"          ) var strGender          : String? = null,
    @SerializedName("intMembers"         ) var intMembers         : String? = null,
    @SerializedName("strCountry"         ) var strCountry         : String? = null,
    @SerializedName("strCountryCode"     ) var strCountryCode     : String? = null,
    @SerializedName("strArtistThumb"     ) var strArtistThumb     : String? = null,
    @SerializedName("strArtistLogo"      ) var strArtistLogo      : String? = null,
    @SerializedName("strArtistCutout"    ) var strArtistCutout    : String? = null,
    @SerializedName("strArtistClearart"  ) var strArtistClearart  : String? = null,
    @SerializedName("strArtistWideThumb" ) var strArtistWideThumb : String? = null,
    @SerializedName("strArtistFanart"    ) var strArtistFanart    : String? = null,
    @SerializedName("strArtistFanart2"   ) var strArtistFanart2   : String? = null,
    @SerializedName("strArtistFanart3"   ) var strArtistFanart3   : String? = null,
    @SerializedName("strArtistFanart4"   ) var strArtistFanart4   : String? = null,
    @SerializedName("strArtistBanner"    ) var strArtistBanner    : String? = null,
    @SerializedName("strMusicBrainzID"   ) var strMusicBrainzID   : String? = null,
    @SerializedName("strISNIcode"        ) var strISNIcode        : String? = null,
    @SerializedName("strLastFMChart"     ) var strLastFMChart     : String? = null,
    @SerializedName("intCharted"         ) var intCharted         : String? = null,
    @SerializedName("strLocked"          ) var strLocked          : String? = null

)